Context file names refactoring
PlatformOfTrust/standards pull request #12
Opened 2019-04-23 07:04 UTC by RomanSavran

- Changes to Buildings according to Sebastian update
- Changing file names to snake case

2019-04-23 07:16 UTC, RomanSavran commented
@soderluk could you please check and merger request? I changed context file names and several requests by Sebastian. DLI ontology is in progress

2019-04-23 08:11 UTC, soderluk requested changes
At least some of the filenames had typos in them, please fix them, and at least run some kind of spellcheck on the files.

2019-04-23 08:11 UTC, soderluk commented on contexts/identity-building_commenrcia_wholesale.jsonld
> +{
This filename? What is commenrcia? Please run a spell check on all filenames. I can't really review 900 filename changes in one PR.

2019-04-23 08:11 UTC, soderluk commented on contexts/identity-building_commenrcial_retail.jsonld
> +{
Same here. Filename typo

2019-04-23 08:11 UTC, soderluk commented on contexts/identity-building_commenrcial_retail_shopping_center.jsonld
> +{
Same here

2019-04-23 08:21 UTC, RomanSavran commented on contexts/identity-building_commenrcia_wholesale.jsonld
> +{
These examples are enough. I relied on new building structure input from Excels provided without spellcheck...

2019-04-25 09:37 UTC, RomanSavran commented on contexts/identity-building_commenrcia_wholesale.jsonld
> +{
@soderluk Please re-check

2019-06-14 13:35 UTC, soderluk commented
@RomanSavran Please abandon this PR as it's redundant and will be replaced with the new features.

2019-08-12 07:40 UTC, closed without merging