Changes to structure
PlatformOfTrust/standards pull request #3
Opened 2019-03-27 23:51 UTC by RomanSavran

- All attributes added to ontology and mapped to domains
- Context and vocabulary files autogenerated
- Ontology file changed due to latest requerements
- Documentation file changed

2019-03-28 12:12 UTC, soderluk requested changes
You have removed all the contexts for links, which we need in the system. Please restore ALL link-*.jsonld contexts, and fix the vocabularies for them.
Also, you removed one of the most important context file, e.g. identity-app.jsonld, please restore the identity-app.jsonld context.

2019-03-28 12:12 UTC, soderluk commented on vocabularies/person.jsonld
> +            }
There should probably be some more information about a person. E.g. optional attributes such as date of birth etc. other useful information that a "person" can have.

2019-03-28 12:12 UTC, soderluk commented on vocabularies/link.jsonld
> +            }
Please revert this file, as links do only have a type. No name or data attribute at the moment.

2019-03-28 12:12 UTC, soderluk commented on README.md
> +All classes and properties can be investigated in [Data Model structure documentation](https://romansavran.github.io/PoT/).
Please point to the standards repository instead.

2019-03-28 12:12 UTC, soderluk commented on README.md
> +All classes and properties can be investigated in [Data Model structure documentation](https://romansavran.github.io/PoT/).
Please point to the standards repository.

2019-03-28 12:17 UTC, soderluk reviewed
The context file identity-data_product.jsonld is removed, please restore it.

2019-03-28 12:19 UTC, soderluk reviewed
The identity-link.jsonld shouldn't exist. A link is not an identity, it's a link.
Links do not have a name or data, only the type

2019-04-01 13:35 UTC, soderluk commented
Could you at the same time update (replace) the base URL from `https://platformoftrust.github.io/standards/` to `https://standards.oftrust.net/`
Should be pretty straight forward to find and replace the previous string with the latter.

2019-04-05 07:32 UTC, RomanSavran commented on vocabularies/person.jsonld
> +            }
Redirected this to Sebastian - he is providing attributes list e.t.c.

2019-04-10 09:21 UTC, soderluk commented
@RomanSavran: Please merge master into your branch, and resolve the conflicts.

2019-04-12 14:00 UTC, RomanSavran commented
@soderluk I completed pot ontology part, but it seems like DLI ontology https://digitalliving.github.io/standards/ontologies/dli.jsonld is outdated (it is missing some classes like Building) even so this classes should be there instead of pot according to latest input I have

Is it possible to provide me access to https://digitalliving.github.io/standards/ so I can add missing classes or how would it better solve this?

2019-04-12 14:51 UTC, soderluk commented
@RomanSavran Did you get the invite?

2019-04-12 16:55 UTC, RomanSavran commented
@soderluk Got it, thank you

2019-04-12 16:56 UTC, RomanSavran commented on vocabularies/person.jsonld
> +            }
Will merge this and work with Sebastian on attributes on Person and other classes in next commits

2019-04-12 16:57 UTC, merged